markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: taogaocn
author: "高涛"
email: taogao.china#gmail.com
name: "高涛的博客"
url: http://www.gaotaoblog.com
domain: www.gaotaoblog.com
all_categories: [
["system", "系统","/posts/system.html"], 
["app", "应用","/posts/app.html"], 
["hardware", "硬件","/posts/hardware.html"],
["tool", "工具","/posts/tool.html"],
["learn", "学习","/posts/learn.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
