markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: taogaocn
author: "高涛"
email: taogao.china#gmail.com
name: "高涛个人博客"
url: http://www.gaotaoblog.com
domain: www.gaotaoblog.com
all_categories: [
["hpc", "高性能计算","/posts/hpc.html"], 
["pds", "并行与分布式系统","/posts/pds.html"],
["data", "大数据分析","/posts/data.html"],
["linux", "Linux系统","/posts/linux.html"], 
["program", "编程相关","/posts/program.html"], 
["learn", "学习心得","/posts/learn.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
